---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: secure-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCATNXmGgibhlaMBYvErc2STz6TZK3yz+XyCWmc1YdRQzogw9GZJSkAGL0Xfes17+QkA9mC9tSmPE/MK6fSydlr9WLW1idOU+TqbLDH1Piazs9u3e+Ee2mD1tmkqEV6D5f+nENaLLV4i88W67dJrZHsI6CLqE59vrnaBF1oglDpkffUQG1e8IYUn4xirBGSnMLUJHeqszQmUh2jW8WLG8lHx8TwSAaX7QPgI77jpSu9pj0ftLs0qx8a398nwJxXb3QxbtRX4PvgZBhgTl97adEN5ws3E76rTLJrsChdcwsRLN32SlhkS66Esoq/a7dfSN96sqf98cPmW5lP9mTHlr47fgfy9NXRXj/i5UhJDyDGXqyoKfVMd2YYM8ZNwAngjzv/lPRGAlygQuLlxvIDXlW1OlQJHdid1+iu1hA8GWnNAMKbkNMpRkHwsH7AIMSM+5PRYZAkul1/s+G5Yq2ZiAO+lSeSIGy+QNfNZYjy3Vd+T6zeVFmZCjrFOmQBgPLxcHJeGstRSrHwu2FyG0ZEvweZyp8fwnQ8m+QRA0IbKrWm8NCCUL2moOcHin2r4BVj0mRmkN1H/LHhZdTFyPPK7eOorh7mS3cySkBwDzb2BqZHBXw+3PgSf9/mHGH5WAnSNx6d/qEantFc11XEI5Nni36OOuyTP5rcPN7/7qf4cx/cvLsQR1jZtnMq7ymuBwF6qSXlfkgLFy7ajw==
    POSTGRES_USER: AgB86fSz1pOTvCdYpRYpjBHLeJWCnD4iLb/qaTUKFwy15+erOPKaRlM9z9irwF/0D86ZrKEkTnerxkoI7Uc8QyWSkMrimxJ3bSzVJu3dhZL6DndRM9w3KaR8G0IIzceCcUHyTbpOkyZ3q4eG+5ZAp4achUQhI7497YL/Gm2cZlQPHrQupi6ddj8u16AsUD9HU8UBCltnu5o+HfKToD5NWdpOFlW//pK0SHeFJcNzTr4ngbSIW4TI98UKhvFrxWjyKZqnWrzO/+inHOKgShJxmvUfBCfTlOpBw/YTr+zsGniqdobT5E+fIg+/q1fepsA/N5yOUUPRizTjQartFteGEkeVfLcNpt4sXM/BgE8mDfoXPPJCteqTctv4mpwa1C0ynez9rDgcR13WLVBYrQ61HLZtFsNvhUgTjLcUBEZY2wP6SPgno1OC30ca/1jmDXE3oNJRfS7fIl73RFzgeUE/X8jZbdvBjgYocQeIdFC5OmRrayw1Stgwo1X+rSAUVNwHA2yCsF7i+BdRJ+eCWnNELHwkvqh63HYHc+KTxHrjqXGMpgoHCvAhUkAlQHJl7bXL3mpNMo7sirso+SgnmXt0/DgYM84VM3qDqK8yR32qC8D16ZWWD9WSFkOnQOCCY+EjIVXusvSpysLYo0xSgoMyB8bKEA9taybyEOuxjUsFt66GtaEaeWOJ8zaGgL0eSp3d5v1sLRMwyPR+0w==
  template:
    metadata:
      name: postgres-secret
      namespace: secure-app
    type: Opaque
